config/routes.rb
Rails.application.routes.draw do
  resources :sample_person_maps
  resources :users
  resources :admins
  resources :activities
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :displayName %>
    <%= form.text_field :displayName %>
  </div>

  <div class="field">
    <%= form.label :netid %>
    <%= form.text_field :netid %>
  </div>

  <div class="field">
    <%= form.label :duid %>
    <%= form.text_field :duid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admins</h1>

<table>
  <thead>
    <tr>
      <th>Displayname</th>
      <th>Netid</th>
      <th>Duid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.displayName %></td>
        <td><%= admin.netid %></td>
        <td><%= admin.duid %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Displayname:</strong>
  <%= @admin.displayName %>
</p>

<p>
  <strong>Netid:</strong>
  <%= @admin.netid %>
</p>

<p>
  <strong>Duid:</strong>
  <%= @admin.duid %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>