config/routes.rb
Rails.application.routes.draw do
  resources :sample_person_maps
  resources :users
  resources :admins
  resources :activities
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sample_person_map.rb
class SamplePersonMap < ApplicationRecord
end

app/controllers/sample_person_maps_controller.rb
class SamplePersonMapsController < ApplicationController
  before_action :set_sample_person_map, only: [:show, :edit, :update, :destroy]

  # GET /sample_person_maps
  # GET /sample_person_maps.json
  def index
    @sample_person_maps = SamplePersonMap.all
  end

  # GET /sample_person_maps/1
  # GET /sample_person_maps/1.json
  def show
  end

  # GET /sample_person_maps/new
  def new
    @sample_person_map = SamplePersonMap.new
  end

  # GET /sample_person_maps/1/edit
  def edit
  end

  # POST /sample_person_maps
  # POST /sample_person_maps.json
  def create
    @sample_person_map = SamplePersonMap.new(sample_person_map_params)

    respond_to do |format|
      if @sample_person_map.save
        format.html { redirect_to @sample_person_map, notice: 'Sample person map was successfully created.' }
        format.json { render :show, status: :created, location: @sample_person_map }
      else
        format.html { render :new }
        format.json { render json: @sample_person_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sample_person_maps/1
  # PATCH/PUT /sample_person_maps/1.json
  def update
    respond_to do |format|
      if @sample_person_map.update(sample_person_map_params)
        format.html { redirect_to @sample_person_map, notice: 'Sample person map was successfully updated.' }
        format.json { render :show, status: :ok, location: @sample_person_map }
      else
        format.html { render :edit }
        format.json { render json: @sample_person_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sample_person_maps/1
  # DELETE /sample_person_maps/1.json
  def destroy
    @sample_person_map.destroy
    respond_to do |format|
      format.html { redirect_to sample_person_maps_url, notice: 'Sample person map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample_person_map
      @sample_person_map = SamplePersonMap.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sample_person_map_params
      params.require(:sample_person_map).permit(:sampleBarCode, :personTestedDuid, :whoDidSampleScanNetid)
    end
end

app/helpers/sample_person_maps_helper.rb
module SamplePersonMapsHelper
end

app/views/sample_person_maps/_form.html.erb
<%= form_with(model: sample_person_map, local: true) do |form| %>
  <% if sample_person_map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sample_person_map.errors.count, "error") %> prohibited this sample_person_map from being saved:</h2>

      <ul>
      <% sample_person_map.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sampleBarCode %>
    <%= form.text_field :sampleBarCode %>
  </div>

  <div class="field">
    <%= form.label :personTestedDuid %>
    <%= form.text_field :personTestedDuid %>
  </div>

  <div class="field">
    <%= form.label :whoDidSampleScanNetid %>
    <%= form.text_field :whoDidSampleScanNetid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sample_person_maps/edit.html.erb
<h1>Editing Sample Person Map</h1>

<%= render 'form', sample_person_map: @sample_person_map %>

<%= link_to 'Show', @sample_person_map %> |
<%= link_to 'Back', sample_person_maps_path %>

app/views/sample_person_maps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sample Person Maps</h1>

<table>
  <thead>
    <tr>
      <th>Samplebarcode</th>
      <th>Persontestedduid</th>
      <th>Whodidsamplescannetid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sample_person_maps.each do |sample_person_map| %>
      <tr>
        <td><%= sample_person_map.sampleBarCode %></td>
        <td><%= sample_person_map.personTestedDuid %></td>
        <td><%= sample_person_map.whoDidSampleScanNetid %></td>
        <td><%= link_to 'Show', sample_person_map %></td>
        <td><%= link_to 'Edit', edit_sample_person_map_path(sample_person_map) %></td>
        <td><%= link_to 'Destroy', sample_person_map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sample Person Map', new_sample_person_map_path %>

app/views/sample_person_maps/new.html.erb
<h1>New Sample Person Map</h1>

<%= render 'form', sample_person_map: @sample_person_map %>

<%= link_to 'Back', sample_person_maps_path %>

app/views/sample_person_maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Samplebarcode:</strong>
  <%= @sample_person_map.sampleBarCode %>
</p>

<p>
  <strong>Persontestedduid:</strong>
  <%= @sample_person_map.personTestedDuid %>
</p>

<p>
  <strong>Whodidsamplescannetid:</strong>
  <%= @sample_person_map.whoDidSampleScanNetid %>
</p>

<%= link_to 'Edit', edit_sample_person_map_path(@sample_person_map) %> |
<%= link_to 'Back', sample_person_maps_path %>