config/routes.rb
Rails.application.routes.draw do
  resources :sample_person_maps
  resources :users
  resources :admins
  resources :activities
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.require(:activity).permit(:action, :note, :netid, :duid)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: activity, local: true) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :action %>
    <%= form.text_field :action %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_field :note %>
  </div>

  <div class="field">
    <%= form.label :netid %>
    <%= form.text_field :netid %>
  </div>

  <div class="field">
    <%= form.label :duid %>
    <%= form.text_field :duid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Activities</h1>

<table>
  <thead>
    <tr>
      <th>Action</th>
      <th>Note</th>
      <th>Netid</th>
      <th>Duid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.action %></td>
        <td><%= activity.note %></td>
        <td><%= activity.netid %></td>
        <td><%= activity.duid %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Action:</strong>
  <%= @activity.action %>
</p>

<p>
  <strong>Note:</strong>
  <%= @activity.note %>
</p>

<p>
  <strong>Netid:</strong>
  <%= @activity.netid %>
</p>

<p>
  <strong>Duid:</strong>
  <%= @activity.duid %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>